$FLETCHER_DIR/hardware/vhlib/util/UtilMisc_pkg.vhd
$FLETCHER_DIR/hardware/vhlib/util/UtilInt_pkg.vhd
$FLETCHER_DIR/hardware/vhlib/util/UtilConv_pkg.vhd
$FLETCHER_DIR/hardware/vhlib/stream/Stream_pkg.vhd
$FLETCHER_DIR/hardware/interconnect/Interconnect_pkg.vhd
$FLETCHER_DIR/hardware/axi/AxiReadConverter.vhd
$FLETCHER_DIR/hardware/arrays/ArrayCmdCtrlMerger.vhd
$FLETCHER_DIR/hardware/arrays/ArrayConfigParse_pkg.vhd
$FLETCHER_DIR/hardware/arrays/ArrayConfig_pkg.vhd
$FLETCHER_DIR/hardware/arrays/Array_pkg.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamArb.vhd
$FLETCHER_DIR/hardware/interconnect/BusReadArbiterVec.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderStruct.vhd
$FLETCHER_DIR/hardware/buffers/Buffer_pkg.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderNull.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderListPrim.vhd
$FLETCHER_DIR/hardware/vhlib/util/UtilStr_pkg.vhd
$FLETCHER_DIR/hardware/interconnect/BusReadBuffer.vhd
$FLETCHER_DIR/hardware/buffers/BufferReaderRespCtrl.vhd
$FLETCHER_DIR/hardware/buffers/BufferReaderResp.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamGearboxSerializer.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamGearboxParallelizer.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamGearbox.vhd
$FLETCHER_DIR/hardware/buffers/BufferReaderPost.vhd
$FLETCHER_DIR/hardware/buffers/BufferReaderCmdGenBusReq.vhd
$FLETCHER_DIR/hardware/buffers/BufferReaderCmd.vhd
$FLETCHER_DIR/hardware/buffers/BufferReader.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderUnlockCombine.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamSync.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamNormalizer.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamSlice.vhd
$FLETCHER_DIR/hardware/vhlib/util/UtilRam1R1W.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamFIFOCounter.vhd
$FLETCHER_DIR/hardware/vhlib/util/UtilRam_pkg.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamFIFO.vhd
$FLETCHER_DIR/hardware/vhlib/stream/StreamBuffer.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderListSyncDecoder.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderListSync.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderList.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderLevel.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReaderArb.vhd
$FLETCHER_DIR/hardware/arrays/ArrayReader.vhd

$FLETCHER_DIR/hardware/parallel_patterns/ParallelPatterns_pkg.vhd
$FLETCHER_DIR/hardware/parallel_patterns/MapStream.vhd
$FLETCHER_DIR/hardware/parallel_patterns/FilterStream.vhd
$FLETCHER_DIR/hardware/parallel_patterns/ReduceStream.vhd
$FLETCHER_DIR/hardware/parallel_patterns/SequenceStream.vhd
$FLETCHER_DIR/hardware/parallel_patterns/StreamSliceArray.vhd
$FLETCHER_DIR/hardware/parallel_patterns/StreamAccumulator.vhd

$CL_DIR/design/vhdl/Forecast_l.gen.vhd
$CL_DIR/design/vhdl/Forecast_Mantle.gen.vhd
$FLETCHER_DIR/hardware/axi/Axi_pkg.vhd
$CL_DIR/design/vhdl/AxiTop.gen.vhd
$CL_DIR/design/vhdl/vhdmmio_pkg.gen.vhd
$CL_DIR/design/vhdl/mmio_pkg.gen.vhd
$CL_DIR/design/vhdl/mmio.gen.vhd
$CL_DIR/design/vhdl/Forecast_pkg.vhd
$CL_DIR/design/vhdl/Forecast.vhd
$CL_DIR/design/vhdl/SumOp.vhd
$CL_DIR/design/vhdl/MergeOp.vhd
$CL_DIR/design/vhdl/ALU.vhd
$CL_DIR/design/vhdl/ReduceStage.vhd
$CL_DIR/design/vhdl/Forecast_Nucleus.gen.vhd
